<a href="https://colab.research.google.com/github/HeeSeok-Kwon/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [2]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)
df
## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding='utf-8')

## 5-2 JSON 형식 저장

In [6]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding='utf-8') as f:
  json.dump(data, f, indent=4, ensure_ascii=False)
## DataFrame을 이용한 저장
# df = pd.DataFrame(data)
# df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)

df = pd.DataFrame([data])
# df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)
df.to_json('output_df.json', orient='columns', indent=4, force_ascii=False)

## 5-3 Pandas Dataframe 데이터 추출

In [13]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
# df

## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist())
print(df.values)

## DataFrame 값 출력
print(df.values.flatten())

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [14]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [16]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df = pd.DataFrame(data)
## CSV, JSON 형식으로 저장
df.to_csv('students_scores.csv')
df.to_json('students_scores.json')

## HTML 형식으로 저장
html_table = df.to_html()
print(html_table)

with open('students_scores.html', 'w') as f:
  f.write(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터공학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>전자공학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>의학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>심리학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

## 5-6 실습 시나리오

## 데이터 수집

In [22]:
import requests

url = "http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty"
api_key = ''

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

response.json()

{'response': {'body': {'totalCount': 40, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '중구', 'pm10Grade': '2', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '한강대로', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '49', 'khaiGrade': '2', 'pm25Value': '27', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '종로구', 'pm10Grade': '2', 'o3Value': '0.049'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '47', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '청계천로', 'pm10Grade': '2', 'o3Value': '0.039'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '40', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '종로', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '33', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.032', 'stationName': '용산구', 'pm10Grade': '2', 'o3Value': '0.020'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '42', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '광진구', 'pm10Grade': '2', 'o3Value': '0.026'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '44', 'khaiGrade': '2', 'pm25Value': '28', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.024', 'stationName': '성동구', 'pm10Grade': '2', 'o3Value': '0.039'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.7', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.037', 'stationName': '강변북로', 'pm10Grade': '2', 'o3Value': '0.027'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.020', 'stationName': '중랑구', 'pm10Grade': '2', 'o3Value': '0.036'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '31', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '동대문구', 'pm10Grade': '2', 'o3Value': '0.049'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '44', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.024', 'stationName': '홍릉로', 'pm10Grade': '2', 'o3Value': '0.040'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '27', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '성북구', 'pm10Grade': '2', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.027', 'stationName': '정릉로', 'pm10Grade': '2', 'o3Value': '0.034'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '도봉구', 'pm10Grade': '2', 'o3Value': '0.043'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '은평구', 'pm10Grade': '2', 'o3Value': '0.035'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '서대문구', 'pm10Grade': '2', 'o3Value': '0.032'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '마포구', 'pm10Grade': '2', 'o3Value': '0.041'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.7', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '50', 'khaiGrade': '2', 'pm25Value': '33', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.033', 'stationName': '신촌로', 'pm10Grade': '2', 'o3Value': '0.033'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '79', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '27', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '강서구', 'pm10Grade': '2', 'o3Value': '0.043'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '79', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '46', 'khaiGrade': '2', 'pm25Value': '33', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '공항대로', 'pm10Grade': '2', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '구로구', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.018', 'stationName': '영등포구', 'pm10Grade': '2', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '49', 'khaiGrade': '2', 'pm25Value': '32', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.030', 'stationName': '영등포로', 'pm10Grade': '2', 'o3Value': '0.027'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '28', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '동작구', 'pm10Grade': '2', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '32', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '동작대로 중앙차로', 'pm10Grade': '2', 'o3Value': '0.036'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '46', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '관악구', 'pm10Grade': '2', 'o3Value': '0.044'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.018', 'stationName': '강남구', 'pm10Grade': '2', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '82', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '46', 'khaiGrade': '2', 'pm25Value': '35', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '서초구', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '50', 'khaiGrade': '2', 'pm25Value': '28', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.023', 'stationName': '도산대로', 'pm10Grade': '2', 'o3Value': '0.041'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '34', 'khaiGrade': '2', 'pm25Value': '24', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.023', 'stationName': '강남대로', 'pm10Grade': '2', 'o3Value': '0.032'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.020', 'stationName': '송파구', 'pm10Grade': '2', 'o3Value': '0.041'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.002', 'coValue': '0.7', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '24', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '강동구', 'pm10Grade': '2', 'o3Value': '0.020'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.030', 'stationName': '천호대로', 'pm10Grade': '2', 'o3Value': '0.018'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '금천구', 'pm10Grade': '2', 'o3Value': '0.036'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '79', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '49', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.025', 'stationName': '시흥대로', 'pm10Grade': '2', 'o3Value': '0.029'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '41', 'khaiGrade': '2', 'pm25Value': '31', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '강북구', 'pm10Grade': '2', 'o3Value': '0.036'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '79', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '27', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.000', 'stationName': '양천구', 'pm10Grade': '2', 'o3Value': '0.041'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '42', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.023', 'stationName': '노원구', 'pm10Grade': '2', 'o3Value': '0.025'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '42', 'khaiGrade': '2', 'pm25Value': '28', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.032', 'stationName': '화랑로', 'pm10Grade': '2', 'o3Value': '0.008'}], 'pageNo': 1, 'numOfRows': 100}, 'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

{'response': {'body': {'totalCount': 40,
   'items': [{'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '37',
     'khaiGrade': '2',
     'pm25Value': '29',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.015',
     'stationName': '중구',
     'pm10Grade': '2',
     'o3Value': '0.052'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '67',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',
     'pm25Value': '22',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.019',
     'stationName': '한강대로',
     'pm10Grade': '2',
     'o3Value': '0.046'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '74',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '49',
     'khaiGrade': '2',
     'pm25Value': '27',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '종로구',
     'pm10Grade': '2',
     'o3Value': '0.049'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '74',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '47',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '청계천로',
     'pm10Grade': '2',
     'o3Value': '0.039'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '40',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.014',
     'stationName': '종로',
     'pm10Grade': '2',
     'o3Value': '0.045'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.002',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '48',
     'khaiGrade': '2',
     'pm25Value': '33',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '2',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.032',
     'stationName': '용산구',
     'pm10Grade': '2',
     'o3Value': '0.020'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.003',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '42',
     'khaiGrade': '2',
     'pm25Value': '25',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.026',
     'stationName': '광진구',
     'pm10Grade': '2',
     'o3Value': '0.026'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '72',
     'so2Value': '0.002',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '44',
     'khaiGrade': '2',
     'pm25Value': '28',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.024',
     'stationName': '성동구',
     'pm10Grade': '2',
     'o3Value': '0.039'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '72',
     'so2Value': '0.003',
     'coValue': '0.7',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '43',
     'khaiGrade': '2',
     'pm25Value': '30',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '2',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.037',
     'stationName': '강변북로',
     'pm10Grade': '2',
     'o3Value': '0.027'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '66',
     'so2Value': '0.002',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '37',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.020',
     'stationName': '중랑구',
     'pm10Grade': '2',
     'o3Value': '0.036'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '74',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',
     'pm25Value': '31',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '동대문구',
     'pm10Grade': '2',
     'o3Value': '0.049'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '44',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.024',
     'stationName': '홍릉로',
     'pm10Grade': '2',
     'o3Value': '0.040'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '39',
     'khaiGrade': '2',
     'pm25Value': '27',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '성북구',
     'pm10Grade': '2',
     'o3Value': '0.042'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.002',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '45',
     'khaiGrade': '2',
     'pm25Value': '29',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.027',
     'stationName': '정릉로',
     'pm10Grade': '2',
     'o3Value': '0.034'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '66',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '36',
     'khaiGrade': '2',
     'pm25Value': '25',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.014',
     'stationName': '도봉구',
     'pm10Grade': '2',
     'o3Value': '0.043'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '60',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '38',
     'khaiGrade': '2',
     'pm25Value': '18',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.012',
     'stationName': '은평구',
     'pm10Grade': '2',
     'o3Value': '0.035'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '74',
     'so2Value': '0.003',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '39',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.019',
     'stationName': '서대문구',
     'pm10Grade': '2',
     'o3Value': '0.032'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '72',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '38',
     'khaiGrade': '2',
     'pm25Value': '23',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '마포구',
     'pm10Grade': '2',
     'o3Value': '0.041'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.003',
     'coValue': '0.7',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '50',
     'khaiGrade': '2',
     'pm25Value': '33',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '2',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.033',
     'stationName': '신촌로',
     'pm10Grade': '2',
     'o3Value': '0.033'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '79',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '45',
     'khaiGrade': '2',
     'pm25Value': '27',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '강서구',
     'pm10Grade': '2',
     'o3Value': '0.043'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '79',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '46',
     'khaiGrade': '2',
     'pm25Value': '33',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '공항대로',
     'pm10Grade': '2',
     'o3Value': '0.050'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.003',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '43',
     'khaiGrade': '2',
     'pm25Value': '18',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '구로구',
     'pm10Grade': '2',
     'o3Value': '0.046'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',
     'pm25Value': '30',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.018',
     'stationName': '영등포구',
     'pm10Grade': '2',
     'o3Value': '0.042'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '62',
     'so2Value': '0.003',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '49',
     'khaiGrade': '2',
     'pm25Value': '32',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.030',
     'stationName': '영등포로',
     'pm10Grade': '2',
     'o3Value': '0.027'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '43',
     'khaiGrade': '2',
     'pm25Value': '28',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.016',
     'stationName': '동작구',
     'pm10Grade': '2',
     'o3Value': '0.042'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '74',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '45',
     'khaiGrade': '2',
     'pm25Value': '32',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.026',
     'stationName': '동작대로 중앙차로',
     'pm10Grade': '2',
     'o3Value': '0.036'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '46',
     'khaiGrade': '2',
     'pm25Value': '26',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.019',
     'stationName': '관악구',
     'pm10Grade': '2',
     'o3Value': '0.044'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '72',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',
     'pm25Value': '29',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.018',
     'stationName': '강남구',
     'pm10Grade': '2',
     'o3Value': '0.052'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '82',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '46',
     'khaiGrade': '2',
     'pm25Value': '35',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.013',
     'stationName': '서초구',
     'pm10Grade': '2',
     'o3Value': '0.046'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '77',
     'so2Value': '0.003',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '50',
     'khaiGrade': '2',
     'pm25Value': '28',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.023',
     'stationName': '도산대로',
     'pm10Grade': '2',
     'o3Value': '0.041'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '60',
     'so2Value': '0.002',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '34',
     'khaiGrade': '2',
     'pm25Value': '24',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.023',
     'stationName': '강남대로',
     'pm10Grade': '2',
     'o3Value': '0.032'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',
     'pm25Value': '29',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.020',
     'stationName': '송파구',
     'pm10Grade': '2',
     'o3Value': '0.041'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '66',
     'so2Value': '0.002',
     'coValue': '0.7',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '36',
     'khaiGrade': '2',
     'pm25Value': '24',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.026',
     'stationName': '강동구',
     'pm10Grade': '2',
     'o3Value': '0.020'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '64',
     'so2Value': '0.002',
     'coValue': '0.6',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '35',
     'khaiGrade': '2',
     'pm25Value': '25',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.030',
     'stationName': '천호대로',
     'pm10Grade': '2',
     'o3Value': '0.018'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '72',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '36',
     'khaiGrade': '2',
     'pm25Value': '22',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.017',
     'stationName': '금천구',
     'pm10Grade': '2',
     'o3Value': '0.036'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '79',
     'so2Value': '0.003',
     'coValue': '0.5',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '1',
     'pm10Value': '49',
     'khaiGrade': '2',
     'pm25Value': '30',
     'sidoName': '서울',
     'no2Flag': None,
     'no2Grade': '1',
     'o3Flag': None,
     'pm25Grade': '2',
     'so2Flag': None,
     'dataTime': '2026-09-13 22:00',
     'coGrade': '1',
     'no2Value': '0.025',
     'stationName': '시흥대로',
     'pm10Grade': '2',
     'o3Value': '0.029'},
    {'so2Grade': '1',
     'coFlag': None,
     'khaiValue': '69',
     'so2Value': '0.002',
     'coValue': '0.4',
     'pm25Flag': None,
     'pm10Flag': None,
     'o3Grade': '2',
     'pm10Value': '41',
     'khaiGrade': '2',

## 데이터 프레임 생성

In [25]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['response']['body']['items']
print(type(data))
print(len(data))
print(data[0])

df = pd.DataFrame(data)
df
df['pm25Flag']

<class 'list'>
40
{'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-13 22:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '중구', 'pm10Grade': '2', 'o3Value': '0.052'}

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
20    None
21    None
22    None
23    None
24    None
25    None
26    None
27    None
28    None
29    None
30    None
31    None
32    None
33    None
34    None
35    None
36    None
37    None
38    None
39    None
Name: pm25Flag, dtype: object

## 다양항 형식으로 데이터 저장

In [27]:
## CSV 형식 데이터 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False) # force_ascii=False -> 한글 깨짐 방지

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')